#/vis/viewer/set/viewpointThetaPhi -90 0
#/vis/viewer/set/viewpointThetaPhi -180 0
/vis/viewer/set/viewpointThetaPhi 240 -30
/vis/viewer/set/background  0.65 0.65 0.65
#/vis/viewer/set/background 0. 0. 0.
/vis/viewer/set/hiddenMarker 1
#/vis/drawVolume
#/vis/scene/add/scale
#/vis/geometry/set/lineWidth all 0 2
#/vis/modeling/trajectories/create/drawByCharge

#/vis/drawVolume
#/vis/scene/add/axes 0 0 0 2 m
#/vis/viewer/set/lightsVector 0 0 0
#/vis/viewer/zoom 10

